import type { Listing } from "@/types/listing";

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();

const hoursAgo = (n: number) =>
  new Date(Date.now() - n * 60 * 60 * 1000).toISOString();

export const BANGALORE_AREAS = [
  "Koramangala",
  "Indiranagar",
  "HSR Layout",
  "Whitefield",
  "Jayanagar",
  "BTM Layout",
  "Marathahalli",
  "Hebbal",
  "JP Nagar",
  "Electronic City",
  "Bellandur",
  "Sarjapur",
];

function listing(overrides: Partial<Listing> & Pick<Listing, "id" | "title">): Listing {
  const postedAt = overrides.createdUtc ?? daysAgo(1);
  return {
    redditPostId: `t3_${overrides.id}`,
    redditUrl: `https://www.reddit.com/r/BangaloreMarketplace/comments/${overrides.id}`,
    subreddit: "bangalore",
    bodyText: null,
    author: "u/anonymous",
    createdUtc: postedAt,
    upvotes: 0,
    numComments: 0,
    thumbnail: null,
    imageUrls: [],
    priceRaw: null,
    priceValue: null,
    currency: "INR",
    locationRaw: null,
    locationNormalized: null,
    category: null,
    condition: "UNKNOWN",
    status: "ACTIVE",
    sourceType: "REDDIT_API",
    syncLastRunAt: postedAt,
    priceConfidence: null,
    locationConfidence: null,
    categoryConfidence: null,
    scamFlag: false,
    duplicateGroupId: null,
    hasImages: false,
    isDeleted: false,
    isRemoved: false,
    lastSeenOnReddit: postedAt,
    createdAt: postedAt,
    updatedAt: postedAt,
    ...overrides,
  };
}

export const MOCK_LISTINGS: Listing[] = [
  listing({
    id: "kora2bhk",
    title: "Fully furnished 2BHK in Koramangala 5th Block · no brokerage",
    bodyText:
      "Spacious 2BHK available for rent. Fully furnished with modern appliances, 24/7 water, covered parking, and a gym in the complex. 5 min walk to Forum Mall. Prefer working professionals or small families. No brokerage.",
    author: "u/koramangala_host",
    createdUtc: hoursAgo(6),
    upvotes: 128,
    numComments: 42,
    imageUrls: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1600",
    ],
    priceRaw: "₹55,000/month",
    priceValue: 55000,
    locationRaw: "Koramangala 5th Block, Bangalore",
    locationNormalized: "Koramangala",
    category: "HOUSING",
    condition: "LIKE_NEW",
    priceConfidence: 0.96,
    locationConfidence: 0.98,
    categoryConfidence: 0.99,
    hasImages: true,
  }),
  listing({
    id: "indirabed",
    title: "Solid teak king size bed with hydraulic storage — barely used",
    bodyText:
      "Selling my teak wood king size bed with hydraulic storage. Bought 8 months ago from Urban Ladder for ₹48,000. Moving out of the city. Pickup from Indiranagar only.",
    author: "u/indira_seller",
    createdUtc: daysAgo(2),
    upvotes: 56,
    numComments: 18,
    imageUrls: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1600",
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1600",
    ],
    priceRaw: "22k",
    priceValue: 22000,
    locationRaw: "Indiranagar, HAL 2nd stage",
    locationNormalized: "Indiranagar",
    category: "FURNITURE",
    condition: "LIKE_NEW",
    priceConfidence: 0.88,
    locationConfidence: 0.97,
    categoryConfidence: 0.97,
    hasImages: true,
  }),
  listing({
    id: "hsrmbp",
    title: 'MacBook Pro 14" M2 Pro · 16GB / 512GB · AppleCare+ till 2026',
    bodyText:
      "Selling my MacBook Pro 14-inch, space grey. Cycle count 62. Comes with original box, charger, and 18 months of AppleCare+ remaining. Meet in HSR.",
    author: "u/hsr_techie",
    createdUtc: daysAgo(3),
    upvotes: 214,
    numComments: 73,
    imageUrls: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1600",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=1600",
    ],
    priceRaw: "₹1,45,000",
    priceValue: 145000,
    locationRaw: "HSR Layout Sector 2",
    locationNormalized: "HSR Layout",
    category: "ELECTRONICS",
    condition: "LIKE_NEW",
    priceConfidence: 0.99,
    locationConfidence: 0.96,
    categoryConfidence: 0.99,
    hasImages: true,
  }),
  listing({
    id: "wfclassic",
    title: "Royal Enfield Classic 350 · 2021 · 18k km · single owner",
    bodyText:
      "Well maintained Classic 350, single owner, all papers clear till 2036. Recently serviced, new tyres. Stealth black. Reason for sale: moving abroad.",
    author: "u/whitefield_rider",
    createdUtc: daysAgo(4),
    upvotes: 89,
    numComments: 31,
    imageUrls: [
      "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1600",
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1600",
    ],
    priceRaw: "1.35L",
    priceValue: 135000,
    locationRaw: "Whitefield, near ITPL",
    locationNormalized: "Whitefield",
    category: "VEHICLES",
    condition: "GOOD",
    priceConfidence: 0.92,
    locationConfidence: 0.97,
    categoryConfidence: 0.99,
    hasImages: true,
  }),
  listing({
    id: "jaytiff",
    title: "Home cook — North Indian tiffin service · Jayanagar",
    bodyText:
      "Experienced home cook offering daily North Indian tiffin service. Lunch + dinner. Hygienic, fresh, and homely. ₹4,500/month for 2 meals per day. Sample available.",
    author: "u/jayanagar_kitchen",
    createdUtc: daysAgo(5),
    upvotes: 312,
    numComments: 104,
    imageUrls: [
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=1600",
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=1600",
    ],
    priceRaw: "₹4,500/mo",
    priceValue: 4500,
    locationRaw: "Jayanagar 4th Block",
    locationNormalized: "Jayanagar",
    category: "SERVICES",
    condition: "UNKNOWN",
    priceConfidence: 0.94,
    locationConfidence: 0.95,
    categoryConfidence: 0.96,
    hasImages: true,
  }),
  listing({
    id: "btmsony",
    title: "Sony WH-1000XM5 · sealed · 10 months warranty left",
    bodyText:
      "Won as a gift, don't use headphones much. Completely sealed box. 10 months warranty left. Meet in BTM or can ship within Bangalore.",
    author: "u/btm_giftee",
    createdUtc: daysAgo(6),
    upvotes: 143,
    numComments: 47,
    imageUrls: [
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=1600",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=1600",
    ],
    priceRaw: "24,500",
    priceValue: 24500,
    locationRaw: "BTM 2nd Stage",
    locationNormalized: "BTM Layout",
    category: "ELECTRONICS",
    condition: "NEW",
    priceConfidence: 0.97,
    locationConfidence: 0.94,
    categoryConfidence: 0.99,
    hasImages: true,
    sourceType: "REDDIT_PUSHSHIFT",
  }),
  listing({
    id: "marasofa",
    title: "IKEA Kivik 3-seater + chaise · beige · 1 year old",
    bodyText:
      "IKEA Kivik 3-seater + chaise, beige. Bought for ₹54,000, selling for ₹28,000. In excellent condition, no stains, pet-free home.",
    author: "u/marathahalli_mover",
    createdUtc: daysAgo(7),
    upvotes: 67,
    numComments: 22,
    imageUrls: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1600",
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1600",
    ],
    priceRaw: "28k",
    priceValue: 28000,
    locationRaw: "Marathahalli near Phoenix",
    locationNormalized: "Marathahalli",
    category: "FURNITURE",
    condition: "LIKE_NEW",
    hasImages: true,
  }),
  listing({
    id: "hebbalyoga",
    title: "Certified yoga instructor · home + group sessions · Hebbal",
    bodyText:
      "Certified hatha and ashtanga yoga instructor, 6 years experience. Home sessions or small group sessions. Flexible timings. Pricing varies by format.",
    author: "u/hebbal_yogi",
    createdUtc: daysAgo(8),
    upvotes: 95,
    numComments: 28,
    imageUrls: [
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1600",
      "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1600",
    ],
    priceRaw: null,
    priceValue: null,
    locationRaw: "Hebbal / Yelahanka",
    locationNormalized: "Hebbal",
    category: "SERVICES",
    condition: "UNKNOWN",
    hasImages: true,
  }),
  listing({
    id: "jpcycle",
    title: "Trek Marlin 7 · Medium frame · includes helmet & lock",
    bodyText:
      "Trek Marlin 7, medium frame, 29er wheels. Bought in 2023. Minor scratches, fully serviced last month. Includes helmet and lock.",
    author: "u/jp_cyclist",
    createdUtc: daysAgo(9),
    upvotes: 54,
    numComments: 14,
    imageUrls: [
      "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=1600",
      "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=1600",
    ],
    priceRaw: "₹42,000",
    priceValue: 42000,
    locationRaw: "JP Nagar 6th Phase",
    locationNormalized: "JP Nagar",
    category: "VEHICLES",
    condition: "GOOD",
    hasImages: true,
  }),
  listing({
    id: "bellguitar",
    title: "Fender Player Stratocaster + Boss Katana Mk2 50W · bundle",
    bodyText:
      "Fender Player Stratocaster (MIM) + Boss Katana Mk2 50W amp. Bundle price. Gigbag and accessories included. Hardly played.",
    author: "u/bellandur_strings",
    createdUtc: daysAgo(10),
    upvotes: 178,
    numComments: 62,
    imageUrls: [
      "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=1600",
      "https://images.unsplash.com/photo-1519508234439-4f23643125c1?w=1600",
    ],
    priceRaw: "65k (bundle)",
    priceValue: 65000,
    locationRaw: "Bellandur Outer Ring Road",
    locationNormalized: "Bellandur",
    category: "HOBBIES",
    condition: "LIKE_NEW",
    hasImages: true,
  }),
  listing({
    id: "indirastudio",
    title: "Studio apartment in Indiranagar · short term OK",
    bodyText:
      "Cozy studio apartment in Indiranagar. Suitable for a single occupant. Available for 3-month minimum stay. All utilities included.",
    author: "u/indira_studio",
    createdUtc: daysAgo(11),
    upvotes: 72,
    numComments: 25,
    imageUrls: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1600",
    ],
    priceRaw: "₹32,000/month",
    priceValue: 32000,
    locationRaw: "Indiranagar 100 feet road",
    locationNormalized: "Indiranagar",
    category: "HOUSING",
    condition: "UNKNOWN",
    hasImages: true,
  }),
  listing({
    id: "sarjcloset",
    title: "Levi's 501 jeans (3) + designer shirts (5) · Size M bundle",
    bodyText:
      "Bundle of 3 Levi's 501 jeans (32x32) and 5 shirts (M). All in great condition. Selling as a bundle only.",
    author: "u/sarjapur_closet",
    createdUtc: daysAgo(14),
    upvotes: 38,
    numComments: 11,
    imageUrls: [],
    priceRaw: "₹4,500",
    priceValue: 4500,
    locationRaw: "Sarjapur Road",
    locationNormalized: "Sarjapur",
    category: "FASHION",
    condition: "GOOD",
    hasImages: false,
    sourceType: "MANUAL",
  }),
];

export function getMockListingById(id: string): Listing | undefined {
  return MOCK_LISTINGS.find((l) => l.id === id);
}
